
import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Modal,
  Platform,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { colors, commonStyles } from "@/styles/commonStyles";
import { IconSymbol } from "@/components/IconSymbol";
import { apiPost } from "@/utils/api";

interface PollingStation {
  countyCode: string;
  countyName: string;
  constituencyCode: string;
  constituencyName: string;
  wardCode: string;
  wardName: string;
  pollingStationCode: string;
  pollingStationName: string;
  registeredVoters: number;
}

const POLLING_STATION_DATA: PollingStation[] = [
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600202",
    pollingStationName: "FADHIL-ADHYM PRIMARY SCHOOL",
    registeredVoters: 612,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600203",
    pollingStationName: "FADHIL-ADHYM PRIMARY SCHOOL",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600301",
    pollingStationName: "MLALEO PRIMARY SCHOOL",
    registeredVoters: 566,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600302",
    pollingStationName: "MLALEO PRIMARY SCHOOL",
    registeredVoters: 565,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600303",
    pollingStationName: "MLALEO PRIMARY SCHOOL",
    registeredVoters: 565,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600304",
    pollingStationName: "MLALEO PRIMARY SCHOOL",
    registeredVoters: 565,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600305",
    pollingStationName: "MLALEO PRIMARY SCHOOL",
    registeredVoters: 565,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600401",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 699,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600402",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600403",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600404",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600405",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600406",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600407",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600408",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600409",
    pollingStationName: "FRERE TOWN PRIMARY SCHOOL",
    registeredVoters: 698,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600501",
    pollingStationName: "MWANDONI KADIRIA GROUNDS",
    registeredVoters: 535,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600502",
    pollingStationName: "MWANDONI KADIRIA GROUNDS",
    registeredVoters: 535,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600503",
    pollingStationName: "MWANDONI KADIRIA GROUNDS",
    registeredVoters: 534,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600601",
    pollingStationName: "VICTORIA BAPTIST PRIMARY SCHOOL",
    registeredVoters: 587,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600602",
    pollingStationName: "VICTORIA BAPTIST PRIMARY SCHOOL",
    registeredVoters: 586,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600603",
    pollingStationName: "VICTORIA BAPTIST PRIMARY SCHOOL",
    registeredVoters: 586,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600701",
    pollingStationName: "SARAJEVO GROUNDS",
    registeredVoters: 605,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600702",
    pollingStationName: "SARAJEVO GROUNDS",
    registeredVoters: 604,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600703",
    pollingStationName: "SARAJEVO GROUNDS",
    registeredVoters: 604,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600704",
    pollingStationName: "SARAJEVO GROUNDS",
    registeredVoters: 604,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001600705",
    pollingStationName: "SARAJEVO GROUNDS",
    registeredVoters: 604,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001603101",
    pollingStationName: "FRERETOWN SECONDARY SCHOOL",
    registeredVoters: 673,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001603102",
    pollingStationName: "FRERETOWN SECONDARY SCHOOL",
    registeredVoters: 672,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001603201",
    pollingStationName: "KHADIJA SECONDARY SCHOOL",
    registeredVoters: 489,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0016",
    wardName: "FRERE TOWN",
    pollingStationCode: "001004001603202",
    pollingStationName: "KHADIJA SECONDARY SCHOOL",
    registeredVoters: 488,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700801",
    pollingStationName: "NATIONAL INDUSTRIAL TRAINING AUTHORI",
    registeredVoters: 651,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700802",
    pollingStationName: "NATIONAL INDUSTRIAL TRAINING AUTHORI",
    registeredVoters: 650,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700803",
    pollingStationName: "NATIONAL INDUSTRIAL TRAINING AUTHORI",
    registeredVoters: 650,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700804",
    pollingStationName: "NATIONAL INDUSTRIAL TRAINING AUTHORI",
    registeredVoters: 650,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700805",
    pollingStationName: "NATIONAL INDUSTRIAL TRAINING AUTHORI",
    registeredVoters: 650,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700806",
    pollingStationName: "NATIONAL INDUSTRIAL TRAINING AUTHORI",
    registeredVoters: 650,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700901",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700902",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700903",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700904",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700905",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700906",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700907",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700908",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700909",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700910",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 680,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700911",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 679,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700912",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 679,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700913",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 679,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001700914",
    pollingStationName: "ZIWA LA NG'OMBE PRIMARY SCHOOL",
    registeredVoters: 679,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701001",
    pollingStationName: "OLIVE REHABILITATION CENTRE - MKUNGU",
    registeredVoters: 669,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701002",
    pollingStationName: "OLIVE REHABILITATION CENTRE - MKUNGU",
    registeredVoters: 669,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701003",
    pollingStationName: "OLIVE REHABILITATION CENTRE - MKUNGU",
    registeredVoters: 669,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701004",
    pollingStationName: "OLIVE REHABILITATION CENTRE - MKUNGU",
    registeredVoters: 669,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701101",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 638,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701102",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 638,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701103",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 638,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701104",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 638,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701105",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 638,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701106",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 638,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701107",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 637,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001701108",
    pollingStationName: "TUMAINI ACADEMY/CHURCH OF CHRIST",
    registeredVoters: 637,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001703301",
    pollingStationName: "KICODEP HALL",
    registeredVoters: 543,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001703302",
    pollingStationName: "KICODEP HALL",
    registeredVoters: 543,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001703303",
    pollingStationName: "KICODEP HALL",
    registeredVoters: 543,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0017",
    wardName: "ZIWA LA NG'OMBE",
    pollingStationCode: "001004001703801",
    pollingStationName: "AZHAR PRIMARY SCHOOL",
    registeredVoters: 472,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801201",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801202",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801203",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801204",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801205",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801206",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801207",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801208",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801209",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801210",
    pollingStationName: "MAWENI PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801501",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801502",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801503",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801504",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801505",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801506",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801507",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801508",
    pollingStationName: "ASK GROUND - GATE 'A'",
    registeredVoters: 636,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801601",
    pollingStationName: "MKOMANI GROUNDS",
    registeredVoters: 687,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801602",
    pollingStationName: "MKOMANI GROUNDS",
    registeredVoters: 687,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801603",
    pollingStationName: "MKOMANI GROUNDS",
    registeredVoters: 687,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001801604",
    pollingStationName: "MKOMANI GROUNDS",
    registeredVoters: 687,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803401",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 642,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803402",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 642,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803403",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 642,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803404",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 642,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803405",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803406",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803407",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803408",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803409",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803410",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803411",
    pollingStationName: "PENTROSE COMMUNITY PRIMARY SCH",
    registeredVoters: 641,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803501",
    pollingStationName: "MAWENI MIXED SECONDARY SCHOOL",
    registeredVoters: 647,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803502",
    pollingStationName: "MAWENI MIXED SECONDARY SCHOOL",
    registeredVoters: 647,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803503",
    pollingStationName: "MAWENI MIXED SECONDARY SCHOOL",
    registeredVoters: 647,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0018",
    wardName: "MKOMANI",
    pollingStationCode: "001004001803504",
    pollingStationName: "MAWENI MIXED SECONDARY SCHOOL",
    registeredVoters: 647,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901701",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901702",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901703",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 668,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901704",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901705",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901706",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901707",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901708",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901709",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901710",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901711",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901712",
    pollingStationName: "KONGOWEA PRIMARY SCHOOL",
    registeredVoters: 667,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901801",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 672,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901802",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 672,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901803",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 672,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901804",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 672,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901805",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 672,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901806",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 671,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901807",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 671,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901808",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 671,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901809",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 671,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901810",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 671,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901811",
    pollingStationName: "KWA KARAMA GROUNDS",
    registeredVoters: 671,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901901",
    pollingStationName: "KENGELENI PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901902",
    pollingStationName: "KENGELENI PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901903",
    pollingStationName: "KENGELENI PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901904",
    pollingStationName: "KENGELENI PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001901905",
    pollingStationName: "KENGELENI PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902001",
    pollingStationName: "MUNICIPAL SOCIAL HALL - KONGOWEA",
    registeredVoters: 656,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902002",
    pollingStationName: "MUNICIPAL SOCIAL HALL - KONGOWEA",
    registeredVoters: 656,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902003",
    pollingStationName: "MUNICIPAL SOCIAL HALL - KONGOWEA",
    registeredVoters: 655,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902004",
    pollingStationName: "MUNICIPAL SOCIAL HALL - KONGOWEA",
    registeredVoters: 655,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902005",
    pollingStationName: "MUNICIPAL SOCIAL HALL - KONGOWEA",
    registeredVoters: 655,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902006",
    pollingStationName: "MUNICIPAL SOCIAL HALL - KONGOWEA",
    registeredVoters: 655,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902101",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 628,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902102",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 628,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902103",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902104",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902105",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902106",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902107",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001902108",
    pollingStationName: "METHODIST CHURCH - KONGOWEA",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001903901",
    pollingStationName: "KONGOWEA SECONDARY SCHOOL",
    registeredVoters: 519,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0019",
    wardName: "KONGOWEA",
    pollingStationCode: "001004001903902",
    pollingStationName: "KONGOWEA SECONDARY SCHOOL",
    registeredVoters: 519,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002301",
    pollingStationName: "BOMBOLULU CULTURAL CENTRE WORK",
    registeredVoters: 688,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002302",
    pollingStationName: "BOMBOLULU CULTURAL CENTRE WORK",
    registeredVoters: 688,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002303",
    pollingStationName: "BOMBOLULU CULTURAL CENTRE WORK",
    registeredVoters: 687,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002401",
    pollingStationName: "BAHAWANI PRIMARY SCHOOL",
    registeredVoters: 539,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002402",
    pollingStationName: "BAHAWANI PRIMARY SCHOOL",
    registeredVoters: 539,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002403",
    pollingStationName: "BAHAWANI PRIMARY SCHOOL",
    registeredVoters: 538,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002404",
    pollingStationName: "BAHAWANI PRIMARY SCHOOL",
    registeredVoters: 538,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002501",
    pollingStationName: "BASHIR PRIMARY SCHOOL",
    registeredVoters: 659,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002502",
    pollingStationName: "BASHIR PRIMARY SCHOOL",
    registeredVoters: 658,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002503",
    pollingStationName: "BASHIR PRIMARY SCHOOL",
    registeredVoters: 658,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002504",
    pollingStationName: "BASHIR PRIMARY SCHOOL",
    registeredVoters: 658,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002601",
    pollingStationName: "KADZANDANI PRIMARY SCHOOL",
    registeredVoters: 620,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002602",
    pollingStationName: "KADZANDANI PRIMARY SCHOOL",
    registeredVoters: 619,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002603",
    pollingStationName: "KADZANDANI PRIMARY SCHOOL",
    registeredVoters: 619,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002604",
    pollingStationName: "KADZANDANI PRIMARY SCHOOL",
    registeredVoters: 619,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002605",
    pollingStationName: "KADZANDANI PRIMARY SCHOOL",
    registeredVoters: 619,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002606",
    pollingStationName: "KADZANDANI PRIMARY SCHOOL",
    registeredVoters: 619,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002701",
    pollingStationName: "MARIANIST POLYTECHNIC",
    registeredVoters: 557,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002702",
    pollingStationName: "MARIANIST POLYTECHNIC",
    registeredVoters: 557,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002703",
    pollingStationName: "MARIANIST POLYTECHNIC",
    registeredVoters: 556,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002801",
    pollingStationName: "SOWETO GROUNDS",
    registeredVoters: 562,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002802",
    pollingStationName: "SOWETO GROUNDS",
    registeredVoters: 562,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002803",
    pollingStationName: "SOWETO GROUNDS",
    registeredVoters: 562,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002804",
    pollingStationName: "SOWETO GROUNDS",
    registeredVoters: 562,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002805",
    pollingStationName: "SOWETO GROUNDS",
    registeredVoters: 562,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002901",
    pollingStationName: "MWATAMBA GROUNDS",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002902",
    pollingStationName: "MWATAMBA GROUNDS",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002903",
    pollingStationName: "MWATAMBA GROUNDS",
    registeredVoters: 627,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002904",
    pollingStationName: "MWATAMBA GROUNDS",
    registeredVoters: 626,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002905",
    pollingStationName: "MWATAMBA GROUNDS",
    registeredVoters: 626,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002002906",
    pollingStationName: "MWATAMBA GROUNDS",
    registeredVoters: 626,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003601",
    pollingStationName: "KWA BULLO PRIMARY/SECONDARY SCH",
    registeredVoters: 616,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003602",
    pollingStationName: "KWA BULLO PRIMARY/SECONDARY SCH",
    registeredVoters: 616,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003603",
    pollingStationName: "KWA BULLO PRIMARY/SECONDARY SCH",
    registeredVoters: 616,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003604",
    pollingStationName: "KWA BULLO PRIMARY/SECONDARY SCH",
    registeredVoters: 616,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003605",
    pollingStationName: "KWA BULLO PRIMARY/SECONDARY SCH",
    registeredVoters: 615,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003606",
    pollingStationName: "KWA BULLO PRIMARY/SECONDARY SCH",
    registeredVoters: 615,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "004",
    constituencyName: "NYALI",
    wardCode: "0020",
    wardName: "KADZANDANI",
    pollingStationCode: "001004002003701",
    pollingStationName: "TEMAN JUNIOR ACADEMY",
    registeredVoters: 610,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100101",
    pollingStationName: "MTONGWE PRIMARY SCHOOL",
    registeredVoters: 590,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100102",
    pollingStationName: "MTONGWE PRIMARY SCHOOL",
    registeredVoters: 589,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100103",
    pollingStationName: "MTONGWE PRIMARY SCHOOL",
    registeredVoters: 589,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100201",
    pollingStationName: "LONGO PRIMARY SCHOOL",
    registeredVoters: 554,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100202",
    pollingStationName: "LONGO PRIMARY SCHOOL",
    registeredVoters: 554,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100203",
    pollingStationName: "LONGO PRIMARY SCHOOL",
    registeredVoters: 553,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100301",
    pollingStationName: "MTONGWE SOCIAL HALL",
    registeredVoters: 625,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100302",
    pollingStationName: "MTONGWE SOCIAL HALL",
    registeredVoters: 625,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100303",
    pollingStationName: "MTONGWE SOCIAL HALL",
    registeredVoters: 625,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100304",
    pollingStationName: "MTONGWE SOCIAL HALL",
    registeredVoters: 625,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100305",
    pollingStationName: "MTONGWE SOCIAL HALL",
    registeredVoters: 625,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100306",
    pollingStationName: "MTONGWE SOCIAL HALL",
    registeredVoters: 624,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100401",
    pollingStationName: "VIJIWENI PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100402",
    pollingStationName: "VIJIWENI PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100403",
    pollingStationName: "VIJIWENI PRIMARY SCHOOL",
    registeredVoters: 644,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100501",
    pollingStationName: "MWANGALA PRIMARY SCHOOL",
    registeredVoters: 373,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100601",
    pollingStationName: "MWEZA PRIMARY SCHOOL",
    registeredVoters: 569,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100602",
    pollingStationName: "MWEZA PRIMARY SCHOOL",
    registeredVoters: 569,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100701",
    pollingStationName: "MKWAJUNI MARKET",
    registeredVoters: 634,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100801",
    pollingStationName: "ST. JOSEPH NURSERY SCHOOL",
    registeredVoters: 609,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100802",
    pollingStationName: "ST. JOSEPH NURSERY SCHOOL",
    registeredVoters: 609,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100803",
    pollingStationName: "ST. JOSEPH NURSERY SCHOOL",
    registeredVoters: 609,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002100804",
    pollingStationName: "ST. JOSEPH NURSERY SCHOOL",
    registeredVoters: 609,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0021",
    wardName: "MTONGWE",
    pollingStationCode: "001005002102701",
    pollingStationName: "MTONGWE VOCATIONAL TRAINING CE",
    registeredVoters: 244,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200901",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200902",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200903",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200904",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200905",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200906",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002200907",
    pollingStationName: "SHIKA ADABU PRIMARY SCHOOL",
    registeredVoters: 645,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201001",
    pollingStationName: "CONSOLATA PRIMARY SCHOOL",
    registeredVoters: 694,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201002",
    pollingStationName: "CONSOLATA PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201003",
    pollingStationName: "CONSOLATA PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201004",
    pollingStationName: "CONSOLATA PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201005",
    pollingStationName: "CONSOLATA PRIMARY SCHOOL",
    registeredVoters: 693,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201101",
    pollingStationName: "VYEMANI PRIMARY SCHOOL",
    registeredVoters: 613,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201102",
    pollingStationName: "VYEMANI PRIMARY SCHOOL",
    registeredVoters: 613,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201103",
    pollingStationName: "VYEMANI PRIMARY SCHOOL",
    registeredVoters: 612,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201201",
    pollingStationName: "VIJIWENI GROUNDS",
    registeredVoters: 624,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201202",
    pollingStationName: "VIJIWENI GROUNDS",
    registeredVoters: 623,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201301",
    pollingStationName: "UJAMAA GROUNDS",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201302",
    pollingStationName: "UJAMAA GROUNDS",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201303",
    pollingStationName: "UJAMAA GROUNDS",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201304",
    pollingStationName: "UJAMAA GROUNDS",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201305",
    pollingStationName: "UJAMAA GROUNDS",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002201306",
    pollingStationName: "UJAMAA GROUNDS",
    registeredVoters: 611,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002202801",
    pollingStationName: "MISHI MBOKO GIRLS SECONDARY SCHO",
    registeredVoters: 34,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002202901",
    pollingStationName: "INSPIRATIONS PRIMARY SCHOOL",
    registeredVoters: 344,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0022",
    wardName: "SHIKA ADABU",
    pollingStationCode: "001005002203201",
    pollingStationName: "SHIKA ADABU SECONDARY SCHOOL",
    registeredVoters: 327,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0023",
    wardName: "BOFU",
    pollingStationCode: "001005002301401",
    pollingStationName: "DARU ULUM MADRASA",
    registeredVoters: 651,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0023",
    wardName: "BOFU",
    pollingStationCode: "001005002301402",
    pollingStationName: "DARU ULUM MADRASA",
    registeredVoters: 651,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0023",
    wardName: "BOFU",
    pollingStationCode: "001005002301403",
    pollingStationName: "DARU ULUM MADRASA",
    registeredVoters: 651,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0023",
    wardName: "BOFU",
    pollingStationCode: "001005002301404",
    pollingStationName: "DARU ULUM MADRASA",
    registeredVoters: 651,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0023",
    wardName: "BOFU",
    pollingStationCode: "001005002301405",
    pollingStationName: "DARU ULUM MADRASA",
    registeredVoters: 651,
  },
  {
    countyCode: "001",
    countyName: "MOMBASA",
    constituencyCode: "005",
    constituencyName: "LIKONI",
    wardCode: "0023",
    wardName: "BOFU",
    pollingStationCode: "001005002301406",
    pollingStationName: "DARU ULUM MADRASA",
    registeredVoters: 651,
  },
];

export default function AdminImportScreen() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [modalTitle, setModalTitle] = useState("");
  const [modalMessage, setModalMessage] = useState("");

  const showAlert = (title: string, message: string) => {
    console.log("Admin Import Alert:", title, message);
    setModalTitle(title);
    setModalMessage(message);
    setModalVisible(true);
  };

  const handleImport = async () => {
    console.log("User tapped Import Polling Stations button");
    setLoading(true);

    try {
      console.log("Importing polling station data:", POLLING_STATION_DATA.length, "stations");
      
      const response = await apiPost("/api/polling-stations/bulk-import", {
        stations: POLLING_STATION_DATA,
      });

      console.log("Import response:", response);

      const successCount = response.summary?.successful || 0;
      const failedCount = response.summary?.failed || 0;
      const totalCount = response.summary?.processed || 0;

      const successMessage = `Successfully imported ${successCount} out of ${totalCount} polling stations.`;
      const failureMessage = failedCount > 0 ? ` ${failedCount} failed.` : "";
      const fullMessage = successMessage + failureMessage;

      showAlert("Import Complete", fullMessage);
    } catch (error: any) {
      console.error("Import error:", error);
      const errorMessage = error?.message || "Failed to import polling stations. Please try again.";
      showAlert("Import Failed", errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const totalStations = POLLING_STATION_DATA.length;
  const uniqueLocations = new Set(POLLING_STATION_DATA.map(s => s.pollingStationName)).size;
  const wards = new Set(POLLING_STATION_DATA.map(s => s.wardName));
  const constituencies = new Set(POLLING_STATION_DATA.map(s => s.constituencyName));
  const wardsList = Array.from(wards).join(", ");
  const constituenciesList = Array.from(constituencies).join(", ");

  return (
    <SafeAreaView style={styles.container} edges={["top"]}>
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => {
            console.log("User tapped back button");
            router.back();
          }}
          style={styles.backButton}
        >
          <IconSymbol
            ios_icon_name="chevron.left"
            android_material_icon_name="arrow-back"
            size={24}
            color={colors.text}
          />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Data Import</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView style={styles.content} contentContainerStyle={styles.contentContainer}>
        <View style={styles.logoContainer}>
          <IconSymbol
            ios_icon_name="square.and.arrow.down"
            android_material_icon_name="cloud-download"
            size={64}
            color={colors.primary}
          />
        </View>

        <Text style={styles.title}>Polling Station Data Import</Text>
        <Text style={styles.subtitle}>
          Import polling station data for Mombasa County
        </Text>

        <View style={styles.infoCard}>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>County:</Text>
            <Text style={styles.infoValue}>MOMBASA (001)</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Constituencies:</Text>
            <Text style={styles.infoValue}>{constituenciesList}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Wards:</Text>
            <Text style={styles.infoValue}>{wardsList}</Text>
          </View>
          <View style={styles.divider} />
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Total Stations:</Text>
            <Text style={styles.infoValueBold}>{totalStations}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Unique Locations:</Text>
            <Text style={styles.infoValueBold}>{uniqueLocations}</Text>
          </View>
        </View>

        <View style={styles.stationsList}>
          <Text style={styles.stationsListTitle}>Polling Stations to Import:</Text>
          {POLLING_STATION_DATA.map((station, index) => {
            const stationCode = station.pollingStationCode;
            const stationName = station.pollingStationName;
            const voters = station.registeredVoters;
            const wardName = station.wardName;
            const constituencyName = station.constituencyName;
            
            return (
              <View key={index} style={styles.stationItem}>
                <View style={styles.stationInfo}>
                  <Text style={styles.stationName}>{stationName}</Text>
                  <View style={styles.stationMetaRow}>
                    <Text style={styles.stationConstituency}>{constituencyName}</Text>
                    <Text style={styles.stationWard}>{wardName}</Text>
                  </View>
                  <Text style={styles.stationCode}>{stationCode}</Text>
                </View>
                <Text style={styles.stationVoters}>{voters}</Text>
              </View>
            );
          })}
        </View>

        <TouchableOpacity
          style={[styles.importButton, loading && styles.importButtonDisabled]}
          onPress={handleImport}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <React.Fragment>
              <IconSymbol
                ios_icon_name="arrow.down.circle.fill"
                android_material_icon_name="cloud-download"
                size={24}
                color="#FFFFFF"
              />
              <Text style={styles.importButtonText}>Import Polling Stations</Text>
            </React.Fragment>
          )}
        </TouchableOpacity>
      </ScrollView>

      <Modal
        visible={modalVisible}
        transparent={true}
        animationType="fade"
        onRequestClose={() => setModalVisible(false)}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <Text style={styles.modalTitle}>{modalTitle}</Text>
            <Text style={styles.modalMessage}>{modalMessage}</Text>
            <TouchableOpacity
              style={styles.modalButton}
              onPress={() => {
                console.log("User dismissed modal");
                setModalVisible(false);
              }}
            >
              <Text style={styles.modalButtonText}>OK</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.text,
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 20,
  },
  infoCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  infoValue: {
    fontSize: 14,
    color: colors.text,
    fontWeight: "500",
    flex: 1,
    textAlign: "right",
  },
  infoValueBold: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: "bold",
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 8,
  },
  stationsList: {
    marginBottom: 24,
  },
  stationsListTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 12,
  },
  stationItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  stationInfo: {
    flex: 1,
  },
  stationName: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 4,
  },
  stationMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  stationConstituency: {
    fontSize: 11,
    color: colors.success || colors.primary,
    fontWeight: "600",
    backgroundColor: colors.successLight || colors.lightGray,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  stationWard: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: "600",
    backgroundColor: colors.primaryLight || colors.lightGray,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  stationCode: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  stationVoters: {
    fontSize: 14,
    fontWeight: "bold",
    color: colors.primary,
    marginLeft: 12,
  },
  importButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  importButtonDisabled: {
    opacity: 0.6,
  },
  importButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 24,
    width: "80%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 12,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 20,
    textAlign: "center",
    lineHeight: 20,
  },
  modalButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
